### PR TITLE
maint: update `kitty.terminfo`

### PR DESCRIPTION
**Pull request by vladdoster**

### CODE REVIEW

**Comment by romkatv** [comment]
`kitty_version` and `kitty_sha256` within `build` would need to be updated at the same time.

**Comment by vladdoster** [comment]
@romkatv Good catch, tyvm. Updating PR.

**Comment by vladdoster** [comment]
~@romkatv I'm unsure of how to calculate the sha256 hash. Is that the hash of the `terminfo` file for the updated version of Kitty?~

Indeed it is

**Comment by romkatv** [comment]
Thank you. Merged.

**Comment by vladdoster** [comment]
wow, quick! :)

**Pull request merged**
